write: 
  replicas: 2
  nodeSelector:
    worknode: "true"

read: 
  replicas: 2
  nodeSelector:
    worknode: "true"

backend: 
  replicas: 2
  nodeSelector:
    worknode: "true"

global:
  auth_enabled: false

minio:
  enabled: true

ingress:
  enabled: true 
  ingressClassName: "nginx"
  hosts:
    - loki.172.20.255.200.nip.io