# gateway: 
#   enabled: true
#   ingress:
#     enabled: true
#     ingressClassName: "nginx"
#     hosts:
#       - host: loki.172.20.255.200.nip.io
#         paths: 
#           - path: / 
write: 
  replicas: 2
  nodeSelector:
    worknode: "true"

read: 
  replicas: 2
  nodeSelector:
    worknode: "true"

backend: 
  replicas: 2
  nodeSelector:
    worknode: "true"


ingress:
  enabled: true 
  ingressClassName: "nginx"
  hosts:
    - loki.172.20.255.200.nip.io